/**
 * Seed script for auto repair pricing data
 *
 * Data sources:
 * - AAA Auto Repair Cost Estimates (2024-2025)
 * - Kelley Blue Book Service Costs
 * - CarMD National Average Repair Costs
 * - RepairPal published averages
 *
 * Pricing is national averages for typical vehicles.
 * Actual costs vary by region, vehicle make/model, and shop labor rates.
 */

interface PricingRecord {
  service_category: string
  service_type: string
  service_label: string
  make?: string
  model?: string
  year_min?: number
  year_max?: number
  region: string
  fair_price_min: number
  fair_price_max: number
  labor_hours_min?: number
  labor_hours_max?: number
  labor_rate_min?: number
  labor_rate_max?: number
  parts_cost_min?: number
  parts_cost_max?: number
  data_source: string
  confidence: number
  notes?: string
}

export const autoRepairPricingData: PricingRecord[] = [
  // BRAKES
  {
    service_category: 'brakes',
    service_type: 'brake_pad_replacement_front',
    service_label: 'Brake Pad Replacement (Front)',
    region: 'national',
    fair_price_min: 150,
    fair_price_max: 300,
    labor_hours_min: 1.0,
    labor_hours_max: 2.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 50,
    parts_cost_max: 150,
    data_source: 'aaa_2024',
    confidence: 90,
    notes: 'Front brake pads, standard replacement',
  },
  {
    service_category: 'brakes',
    service_type: 'brake_pad_replacement_rear',
    service_label: 'Brake Pad Replacement (Rear)',
    region: 'national',
    fair_price_min: 150,
    fair_price_max: 300,
    labor_hours_min: 1.0,
    labor_hours_max: 2.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 50,
    parts_cost_max: 150,
    data_source: 'aaa_2024',
    confidence: 90,
    notes: 'Rear brake pads, standard replacement',
  },
  {
    service_category: 'brakes',
    service_type: 'brake_rotor_replacement_front',
    service_label: 'Brake Rotor Replacement (Front)',
    region: 'national',
    fair_price_min: 300,
    fair_price_max: 550,
    labor_hours_min: 1.5,
    labor_hours_max: 3.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 150,
    parts_cost_max: 300,
    data_source: 'carmd_2024',
    confidence: 85,
    notes: 'Front rotors with pads',
  },
  {
    service_category: 'brakes',
    service_type: 'brake_caliper_replacement',
    service_label: 'Brake Caliper Replacement',
    region: 'national',
    fair_price_min: 350,
    fair_price_max: 800,
    labor_hours_min: 2.0,
    labor_hours_max: 4.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 150,
    parts_cost_max: 450,
    data_source: 'repairpal',
    confidence: 85,
    notes: 'Single caliper replacement',
  },

  // OIL CHANGE & FLUIDS
  {
    service_category: 'maintenance',
    service_type: 'oil_change_conventional',
    service_label: 'Oil Change (Conventional)',
    region: 'national',
    fair_price_min: 30,
    fair_price_max: 60,
    labor_hours_min: 0.3,
    labor_hours_max: 0.5,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 15,
    parts_cost_max: 30,
    data_source: 'aaa_2024',
    confidence: 95,
    notes: 'Standard oil change with conventional oil',
  },
  {
    service_category: 'maintenance',
    service_type: 'oil_change_synthetic',
    service_label: 'Oil Change (Synthetic)',
    region: 'national',
    fair_price_min: 50,
    fair_price_max: 90,
    labor_hours_min: 0.3,
    labor_hours_max: 0.5,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 30,
    parts_cost_max: 60,
    data_source: 'aaa_2024',
    confidence: 95,
    notes: 'Oil change with synthetic oil',
  },
  {
    service_category: 'maintenance',
    service_type: 'transmission_fluid_change',
    service_label: 'Transmission Fluid Change',
    region: 'national',
    fair_price_min: 150,
    fair_price_max: 250,
    labor_hours_min: 1.0,
    labor_hours_max: 2.0,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 50,
    parts_cost_max: 100,
    data_source: 'kbb_2024',
    confidence: 85,
    notes: 'Drain and fill, not flush',
  },
  {
    service_category: 'maintenance',
    service_type: 'coolant_flush',
    service_label: 'Coolant Flush',
    region: 'national',
    fair_price_min: 100,
    fair_price_max: 180,
    labor_hours_min: 0.8,
    labor_hours_max: 1.5,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 30,
    parts_cost_max: 60,
    data_source: 'repairpal',
    confidence: 80,
  },

  // TIRES
  {
    service_category: 'tires',
    service_type: 'tire_rotation',
    service_label: 'Tire Rotation',
    region: 'national',
    fair_price_min: 20,
    fair_price_max: 50,
    labor_hours_min: 0.3,
    labor_hours_max: 0.5,
    labor_rate_min: 80,
    labor_rate_max: 100,
    parts_cost_min: 0,
    parts_cost_max: 0,
    data_source: 'aaa_2024',
    confidence: 95,
  },
  {
    service_category: 'tires',
    service_type: 'wheel_alignment',
    service_label: 'Wheel Alignment',
    region: 'national',
    fair_price_min: 75,
    fair_price_max: 150,
    labor_hours_min: 1.0,
    labor_hours_max: 1.5,
    labor_rate_min: 75,
    labor_rate_max: 120,
    parts_cost_min: 0,
    parts_cost_max: 30,
    data_source: 'aaa_2024',
    confidence: 90,
  },
  {
    service_category: 'tires',
    service_type: 'tire_balance',
    service_label: 'Tire Balance (All 4)',
    region: 'national',
    fair_price_min: 40,
    fair_price_max: 80,
    labor_hours_min: 0.5,
    labor_hours_max: 1.0,
    labor_rate_min: 80,
    labor_rate_max: 100,
    parts_cost_min: 0,
    parts_cost_max: 20,
    data_source: 'manual',
    confidence: 85,
  },

  // BATTERY & ELECTRICAL
  {
    service_category: 'electrical',
    service_type: 'battery_replacement',
    service_label: 'Battery Replacement',
    region: 'national',
    fair_price_min: 100,
    fair_price_max: 250,
    labor_hours_min: 0.3,
    labor_hours_max: 1.0,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 80,
    parts_cost_max: 200,
    data_source: 'aaa_2024',
    confidence: 90,
  },
  {
    service_category: 'electrical',
    service_type: 'alternator_replacement',
    service_label: 'Alternator Replacement',
    region: 'national',
    fair_price_min: 400,
    fair_price_max: 900,
    labor_hours_min: 2.0,
    labor_hours_max: 4.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 200,
    parts_cost_max: 600,
    data_source: 'carmd_2024',
    confidence: 85,
  },
  {
    service_category: 'electrical',
    service_type: 'starter_replacement',
    service_label: 'Starter Replacement',
    region: 'national',
    fair_price_min: 350,
    fair_price_max: 800,
    labor_hours_min: 1.5,
    labor_hours_max: 3.5,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 150,
    parts_cost_max: 450,
    data_source: 'carmd_2024',
    confidence: 85,
  },

  // ENGINE
  {
    service_category: 'engine',
    service_type: 'spark_plug_replacement',
    service_label: 'Spark Plug Replacement',
    region: 'national',
    fair_price_min: 100,
    fair_price_max: 300,
    labor_hours_min: 0.8,
    labor_hours_max: 2.5,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 40,
    parts_cost_max: 150,
    data_source: 'repairpal',
    confidence: 80,
    notes: 'Varies by engine configuration (V6/V8 more expensive)',
  },
  {
    service_category: 'engine',
    service_type: 'timing_belt_replacement',
    service_label: 'Timing Belt Replacement',
    region: 'national',
    fair_price_min: 500,
    fair_price_max: 1200,
    labor_hours_min: 4.0,
    labor_hours_max: 8.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 150,
    parts_cost_max: 400,
    data_source: 'carmd_2024',
    confidence: 85,
    notes: 'Often includes water pump replacement',
  },
  {
    service_category: 'engine',
    service_type: 'water_pump_replacement',
    service_label: 'Water Pump Replacement',
    region: 'national',
    fair_price_min: 400,
    fair_price_max: 900,
    labor_hours_min: 2.5,
    labor_hours_max: 5.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 100,
    parts_cost_max: 300,
    data_source: 'repairpal',
    confidence: 80,
  },
  {
    service_category: 'engine',
    service_type: 'serpentine_belt_replacement',
    service_label: 'Serpentine Belt Replacement',
    region: 'national',
    fair_price_min: 80,
    fair_price_max: 200,
    labor_hours_min: 0.5,
    labor_hours_max: 1.5,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 25,
    parts_cost_max: 75,
    data_source: 'aaa_2024',
    confidence: 85,
  },
  {
    service_category: 'engine',
    service_type: 'fuel_pump_replacement',
    service_label: 'Fuel Pump Replacement',
    region: 'national',
    fair_price_min: 500,
    fair_price_max: 1100,
    labor_hours_min: 3.0,
    labor_hours_max: 6.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 200,
    parts_cost_max: 600,
    data_source: 'carmd_2024',
    confidence: 80,
  },

  // SUSPENSION
  {
    service_category: 'suspension',
    service_type: 'shock_absorber_replacement',
    service_label: 'Shock Absorber Replacement (Pair)',
    region: 'national',
    fair_price_min: 350,
    fair_price_max: 750,
    labor_hours_min: 2.0,
    labor_hours_max: 4.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 150,
    parts_cost_max: 400,
    data_source: 'repairpal',
    confidence: 80,
  },
  {
    service_category: 'suspension',
    service_type: 'strut_replacement',
    service_label: 'Strut Replacement (Pair)',
    region: 'national',
    fair_price_min: 500,
    fair_price_max: 1200,
    labor_hours_min: 3.0,
    labor_hours_max: 6.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 250,
    parts_cost_max: 700,
    data_source: 'carmd_2024',
    confidence: 80,
  },
  {
    service_category: 'suspension',
    service_type: 'tie_rod_replacement',
    service_label: 'Tie Rod End Replacement',
    region: 'national',
    fair_price_min: 150,
    fair_price_max: 400,
    labor_hours_min: 1.0,
    labor_hours_max: 2.5,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 50,
    parts_cost_max: 150,
    data_source: 'repairpal',
    confidence: 75,
  },

  // EXHAUST
  {
    service_category: 'exhaust',
    service_type: 'muffler_replacement',
    service_label: 'Muffler Replacement',
    region: 'national',
    fair_price_min: 150,
    fair_price_max: 400,
    labor_hours_min: 1.0,
    labor_hours_max: 2.5,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 75,
    parts_cost_max: 250,
    data_source: 'manual',
    confidence: 75,
  },
  {
    service_category: 'exhaust',
    service_type: 'catalytic_converter_replacement',
    service_label: 'Catalytic Converter Replacement',
    region: 'national',
    fair_price_min: 1000,
    fair_price_max: 2500,
    labor_hours_min: 2.0,
    labor_hours_max: 5.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 800,
    parts_cost_max: 2000,
    data_source: 'carmd_2024',
    confidence: 80,
    notes: 'High cost due to precious metals in part',
  },

  // AC & HEATING
  {
    service_category: 'hvac',
    service_type: 'ac_recharge',
    service_label: 'AC Recharge',
    region: 'national',
    fair_price_min: 100,
    fair_price_max: 250,
    labor_hours_min: 0.5,
    labor_hours_max: 1.5,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 30,
    parts_cost_max: 100,
    data_source: 'repairpal',
    confidence: 85,
  },
  {
    service_category: 'hvac',
    service_type: 'ac_compressor_replacement',
    service_label: 'AC Compressor Replacement',
    region: 'national',
    fair_price_min: 600,
    fair_price_max: 1400,
    labor_hours_min: 3.0,
    labor_hours_max: 6.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 300,
    parts_cost_max: 800,
    data_source: 'carmd_2024',
    confidence: 75,
  },
  {
    service_category: 'hvac',
    service_type: 'heater_core_replacement',
    service_label: 'Heater Core Replacement',
    region: 'national',
    fair_price_min: 500,
    fair_price_max: 1200,
    labor_hours_min: 4.0,
    labor_hours_max: 8.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 100,
    parts_cost_max: 300,
    data_source: 'repairpal',
    confidence: 70,
    notes: 'Labor intensive, requires dashboard removal',
  },

  // TRANSMISSION
  {
    service_category: 'transmission',
    service_type: 'transmission_rebuild',
    service_label: 'Transmission Rebuild',
    region: 'national',
    fair_price_min: 1800,
    fair_price_max: 3500,
    labor_hours_min: 10.0,
    labor_hours_max: 20.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 800,
    parts_cost_max: 1500,
    data_source: 'carmd_2024',
    confidence: 75,
    notes: 'Major repair, consider replacement option',
  },

  // COOLING SYSTEM
  {
    service_category: 'cooling',
    service_type: 'radiator_replacement',
    service_label: 'Radiator Replacement',
    region: 'national',
    fair_price_min: 400,
    fair_price_max: 1000,
    labor_hours_min: 2.0,
    labor_hours_max: 5.0,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 200,
    parts_cost_max: 600,
    data_source: 'repairpal',
    confidence: 80,
  },
  {
    service_category: 'cooling',
    service_type: 'thermostat_replacement',
    service_label: 'Thermostat Replacement',
    region: 'national',
    fair_price_min: 150,
    fair_price_max: 350,
    labor_hours_min: 1.0,
    labor_hours_max: 2.0,
    labor_rate_min: 80,
    labor_rate_max: 120,
    parts_cost_min: 20,
    parts_cost_max: 100,
    data_source: 'aaa_2024',
    confidence: 85,
  },

  // DIAGNOSTICS
  {
    service_category: 'diagnostic',
    service_type: 'diagnostic_scan',
    service_label: 'Diagnostic Scan / Check Engine Light',
    region: 'national',
    fair_price_min: 50,
    fair_price_max: 150,
    labor_hours_min: 0.5,
    labor_hours_max: 1.5,
    labor_rate_min: 80,
    labor_rate_max: 150,
    parts_cost_min: 0,
    parts_cost_max: 0,
    data_source: 'manual',
    confidence: 85,
    notes: 'Should not be charged if repair is performed',
  },
]

// Export count for verification
export const TOTAL_SERVICES = autoRepairPricingData.length

console.log(`Loaded ${TOTAL_SERVICES} auto repair pricing records`)
